# Generated by Django 5.0.6 on 2024-06-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('descripition', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('review_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('comment', models.CharField(max_length=8000)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
